version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    environment:
      NODE_ENV: testing
      POSTGRESQL_HOST: pg
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: test
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
      - pg
    depends_on:
      - mysql
      - pg
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wizard
    networks:
      - backend
  pg:
    image: postgres:11-alpine
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
