service: websocket-test
frameworkVersion: 4

custom:
  tableName: SessionTable
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages: dev
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - "aws-sdk"
        - "@aws-sdk"
    packager: 'npm'
    excludeFiles: src/**/*.test.js

plugins:
  - serverless-webpack
  #  - serverless-plugin-optimize
  # - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    SESSION_TABLE_NAME: ${self:custom.tableName}

functions:
  connectHandler:
    handler: src/handlers/connect.handler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: src/handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  offerHandler:
    handler: src/handlers/offer.handler
    events:
      - websocket:
          route: offer
  iceHandler:
    handler: src/handlers/ice.handler
    events:
      - websocket:
          route: ice
  defaultHandler:
    handler: src/handlers/default.handler
    events:
      - websocket:
          route: $default

resources:
  Resources:
    SessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: state
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: state
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
