service: websocket-test

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules:
      forceExclude:
        - "aws-sdk"
        - "@aws-sdk"
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

plugins:
  - serverless-webpack
#  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  configValidationMode: erro
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

#  environment:
#    CONNECTION_DB_TABLE: ${self:resources.Resources.MessageTable.Properties.TableName}
#  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - "dynamodb:PutItem"
#        - "dynamodb:GetItem"
#        - "dynamodb:DeleteItem"
#        - "dynamodb:Scan"
#      Resource:
#        - Fn::GetAtt: [websocket-Table, Arn]
#    - Effect: Allow
#      Action:
#        - "execute-api:ManageConnections"
#      Resource:
#        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connectHandler:
    handler: src/handlers/connect.handler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: src/handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: src/handlers/default.handler
    events:
      - websocket:
          route: $default
      - lambda:
  offerHandler:
    handler: src/handlers/commands.handler
    events:
      - websocket:
          route: offer
  answerHandler:
    handler: src/handlers/commands.handler
    events:
      - websocket:
          route: answer
  iceHandler:
    handler: src/handlers/commands.handler
    events:
      - websocket:
          route: ice

#resources:
#  Resources:
#    MessageTable:
#      Type: "AWS::DynamoDB::Table"
#      Properties:
#        AttributeDefinitions:
#          - AttributeName: "connectionId"
#            AttributeType: "S"
#        KeySchema:
#          - AttributeName: "connectionId"
#            KeyType: "HASH"
#        BillingMode: PAY_PER_REQUEST
#        TableName: "AppConnectionTable"
